### ISSUE TITLE
Support for HubSpot requiring migration to private apps

### ISSUE THREAD

**Issue by shaunroot** [Chinchilla-Software-Com/HubSpot.NET#11]
> API Keys have been [one of three authentication methods supported by HubSpot](https://developers.hubspot.com/docs/api/intro-to-auth) APIs. However, as part of ongoing efforts to protect our customer's data, we will be sunsetting API Keys.
> 
> As a result of this change, integrations will instead be required to work with [Private Apps](https://developers.hubspot.com/docs/api/private-apps). Private Apps offer tighter security and allow more granular control over your integrations and account data than legacy API keys.

https://developers.hubspot.com/docs/api/migrate-an-api-key-integration-to-a-private-app

**Comment by cdmdotnet** [comment]
The library handles PATs. There are (should) be tests to show how to do this.

**Comment by shaunroot** [comment]
_I see. It's just not on Nuget yet. Thanks_

Edit: was replaced by Chinchilla.HubSpot.NET
