### ISSUE TITLE
OAuth - Unsupported media type.

### ISSUE THREAD

**Issue by DaltonKirk** [Chinchilla-Software-Com/HubSpot.NET#16]
When trying to Authorize or Refresh an OAuth token, like this:
![image](https://user-images.githubusercontent.com/22774653/196217527-acd8122a-ed9b-4062-bbb8-aec56eb4ae9b.png)

There is an error and the returned token is null:
![image](https://user-images.githubusercontent.com/22774653/196217198-5fd7f34b-9461-4add-b6bd-9e9357517d9f.png)

**Comment by DaltonKirk** [comment]
I have created a PR #17 with a fix

**Comment by cdmdotnet** [comment]
New packages submitted. The merge was interesting as your based the PR off master, which we don't use... we use trunk.

**Comment by DaltonKirk** [comment]
Oh sorry about that. Will this fox be making its way into a nuget package update? I’m currently using the source code in my project but would like to switch to the nuget package if it gets updated.

**Comment by cdmdotnet** [comment]
Nuget packages already updated.
