### ISSUE TITLE
HubSpot API Key Sunset: Private App support

### ISSUE THREAD

**Issue by ChristianBjerre** [Chinchilla-Software-Com/HubSpot.NET#18]
HubSpot sunset the API key by 30 November 2022. It is replaced by a private key, where you can specify access on a fine-grained level.

[https://developers.hubspot.com/changelog/upcoming-api-key-sunset](https://developers.hubspot.com/changelog/upcoming-api-key-sunset)

[Migration Guide](https://developers.hubspot.com/docs/api/migrate-an-api-key-integration-to-a-private-app)

Acceptance criteria:
* HubSpot.NET supports Private Key for HubSpot API access

**Comment by ChristianBjerre** [comment]
I have made the changes and they work with most tests for private key.

For some reason I cannot create the pull request, so I have attached the patch file (with TXT extension).

Anyone who can help?

[Issue_18_HubSpot_private_key.txt](https://github.com/Chinchilla-Software-Com/HubSpot.NET/files/9894589/Issue_18_HubSpot_private_key.txt)

**Comment by cdmdotnet** [comment]
Sorry, this diff file has too many conflicts - every files clashes with the primary branch trunk.
I'm guessing you've made these changes against a branch that isn't the primary branch. Please try again using trunk as as your branch.

**Comment by ChristianBjerre** [comment]
Sorry. Can see that I picked the wrong branch.
