### ISSUE TITLE
Support pat keys

### ISSUE THREAD

**Issue by TP125487** [Chinchilla-Software-Com/HubSpot.NET#29]
I am using 1.5.2 and pat keys do indeed not work. [Here](https://github.com/Chinchilla-Software-Com/HubSpot.NET/issues/11#issuecomment-1244639844) you say pat keys are supported, but they aren't.
Bearer Auth must be used for pat keys.
```
    public HubSpotBaseClient(string apiKey)
    {
      _apiKey = apiKey;
      _mode = HubSpotAuthenticationMode.HAPIKEY;
      Initialise();
    }
```

**Comment by cdmdotnet** [comment]
You've quoted lines 35 - 40

Look at the next constructor on lines 42 - 50 - that is the constructor to use with PATs

>         /// <summary>
>        /// Creates a HubSpot client with the authentication scheme OAUTH.
>        /// </summary>
>        public HubSpotBaseClient(HubSpotToken token)
>        {
>            _token = token;
>            _mode = HubSpotAuthenticationMode.OAUTH;
>            Initialise();
>        }

**Comment by TP125487** [comment]
That's OAUTH. PAT is a private App Key that starts with pat-. HubSpotClient is handling it correctly

https://github.com/skarpdev/dotnetcore-hubspot-client/blob/c4b826ce5b72bcd182802221c3572d5ad5b0a914/src/Core/HubSpotBaseClient.cs#L269

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by cdmdotnet** [comment]
Enter your PAT as the AccessToken in the token.

**Comment by TP125487** [comment]
While that may indeed work I dont think thats a proper implementation for simple PATs as HubSpotToken is meant for OAUTH. I'd call it a hack that luckily works.

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cdmdotnet** [comment]
Your opinions have been noted
