### ISSUE TITLE
Merge upstream master with 0.6.19 as branch 0.8.13

### ISSUE THREAD

**Issue by cdmdotnet** [Chinchilla-Software-Com/HubSpot.NET#3]
See branch 0.8.13

**Comment by lakesol** [comment]
Hi @cdmdotnet , hope you are well.   Any update on this merge?  I am looking to use some of your code as you know, but I also now need OAUTH.  Do you have an ETA?

Thanks
Lake

**Comment by cdmdotnet** [comment]
Sorry about the delay. Missed the notification of your PR. Reviewing today.

**Comment by cdmdotnet** [comment]
We've reviewed all the upstream code and hit an issue. All the serialisation code was removed and now none of the upstream API code actually works. It's really quite disappointing. Addressing the serialisation is looking like an effort to either understand where the original code was heading, or restore the original serialisation code and move forward.

If OAuth is what you're really looking for, I can isolate that out and do an interim merge adding OAuth.

**Comment by lakesol** [comment]
Hi @cdmdotnet thanks for the update.  Just wondering if we should have a chat to discuss, so you have any channels I can reach you to arrange?

It would be good to understand the issues you are seeing with the API logic.

**Comment by cdmdotnet** [comment]
I've just pushed up the code. It's in branch 0.8.13. It compiles, however most methods return objects with no properties or values. The 0.6.x branches have a few blocks of code to handle the seralisation methodology HubSpot operates. It probably isn't hard to bring it over, but understanding why their removed it and what their intention was from code alone is difficult but also important. 

I'll have a look at my calendar and see where I have time for a zoom call. What timezone are you in? I'm currently in NZ.

**Comment by lakesol** [comment]
Thanks for the update.  I will take a look at the branch tomorrow when in the office.  I will see if I can shed any light on the issues.

Regarding a meeting I am in the UK, but happy to do a meeting one day at say 21:00-22:00 UK time if you are free.

**Comment by cdmdotnet** [comment]
That time should work. I have either my Monday (your Sunday) or my Tuesday (your Monday) next week if either of those work.

**Comment by lakesol** [comment]
Tuesday NZ (Monday UK) @ 21:00 should work.  It will give me some time to do test testing/investigation.  If I ping an email to your company info email address will you be pick that up?

**Comment by lakesol** [comment]
Email sent.  Speak soon.

**Comment by cdmdotnet** [comment]
Upstream is being abandoned as it is not in a stable condition.
The dependency on Flurl has been removed and OAuth supported added to branch 1.0. This should be released soon.

Our other collaboration is still on going, but upstream is not going to be used.
