### ISSUE TITLE
Associations API

### ISSUE THREAD

**Issue by hakimio** [Chinchilla-Software-Com/HubSpot.NET#5]
Are there any plans to implement the [Associations API](https://legacydocs.hubspot.com/docs/methods/crm-associations/crm-associations-overview)?
https://github.com/hubspot-net/HubSpot.NET/issues/59

**Comment by cdmdotnet** [comment]
We utilise that API for the following relationships
Contact
Company
Deal

Is there a specific relationship you are referring to or are you wanting a simple wrapper around that API?

**Comment by hakimio** [comment]
I know that I can set `AssociatedCompanyId` on a `Contact` and use `api.Company.GetAssociations(company)` to get associated contacts, but I was wondering if we could use [the associations API](https://legacydocs.hubspot.com/docs/methods/crm-associations/associate-objects) to map single contact to multiple companies. Anyway, it would be a nice to have but not a must have feature.

On unrelated note, there seems to be some issue with `ap.Company.Search()` result (`CompanySearchHubSpotModel<Company>`) deserialization. Even `paging.next.after` is set on the JSON response, `Paging.Next` is set to `null` in the deserialized result.

![image](https://user-images.githubusercontent.com/768105/154649334-ba6dd695-d429-478c-950d-68be2f74e7b9.png)

Any idea why that might be happening?

**Comment by cdmdotnet** [comment]
Please keep issues to one topic at a time and raise a separate issue for the `.Company.Search` observation.

**Comment by cdmdotnet** [comment]
Mapping contacts to multiple companies is already raised as issue #4 .
