### ISSUE TITLE
"Paging.Next" is not set in "Company.Search()" result

### ISSUE THREAD

**Issue by hakimio** [Chinchilla-Software-Com/HubSpot.NET#8]
**Describe the bug**
When searching for a company with `Company.Search()` method, `Paging.Next` is set to `null` in deserialized result, even `paging.next.after` is set in the JSON response.

**Repro Steps**
- Search for a company using the `Company.Search()` method with `Limit` parameter set to lower number than the total result count.
- Inspect `Paging.Next` in the search result (`CompanySearchHubSpotModel<Company>`).

**Expected behavior**
`Paging.Next` should be set.

**Screenshots**
![image](https://user-images.githubusercontent.com/768105/155130265-d4f4433b-23ca-44b0-a189-fec2b688f623.png)

**Comment by hakimio** [comment]
The issue seems to be in [`RequestDataConverter.ConvertSingleEntity()`](https://github.com/Chinchilla-Software-Com/HubSpot.NET/blob/96a88c023e23808e6390460cb2bc5d1f2d53fbf6/HubSpot.NET/Core/Requests/RequestDataConverter.cs#L194) which doesn't process `PagingModel` correctly. It exits [here](https://github.com/Chinchilla-Software-Com/HubSpot.NET/blob/96a88c023e23808e6390460cb2bc5d1f2d53fbf6/HubSpot.NET/Core/Requests/RequestDataConverter.cs#L266) without populating `Next` property.

Screenshots from the debugger:

![image](https://user-images.githubusercontent.com/768105/155150204-ad546f79-e774-4498-b9f4-320ae1d7a30f.png)

![image](https://user-images.githubusercontent.com/768105/155149440-0c603b27-7fdc-4ad0-8f87-939f73121717.png)

**Comment by cdmdotnet** [comment]
Resolved with release 0.6.20.1 https://github.com/Chinchilla-Software-Com/HubSpot.NET/releases/tag/0.6.20.1

**Comment by hakimio** [comment]
@cdmdotnet Thanks for fixing the bug. It seems to be working well now.
Just few simple recommendations/requests:
- Can you use `master` branch for stable versions and just use tags to indicate version number instead of creating a new branch for every release? It would be a lot better for anyone who just wants to read the code or open a new PR.
- The `nuget` badge and link (the one in "Getting Started" section) in the README points to the wrong nuget package. Can you update it?
- Maybe there should be some way to promote this library? If `hubspot-net/HubSpot.NET` is no longer maintained, maybe they would be willing to admit that in their README and point to this repository? Or HubSpot itself could recommend this library? Would be a lot easier for others to find it that way.
