### ISSUE TITLE
NuGet Pkg out of date?

### ISSUE THREAD

**Issue by zedle** [Chinchilla-Software-Com/HubSpot.NET#9]
Hello, I noticed here on github the version is higher than the currently provided one on nuget.org (https://www.nuget.org/packages/_SquaredUp.HubSpot.NET) - is there any way this could be updated?

Much appreciated!

**Comment by cdmdotnet** [comment]
We had a contribution from the community which was awaiting further commits, mostly around testing.
I'll review the changes and see if we can push out a new package today/tomorrow

**Comment by cdmdotnet** [comment]
I've merged the contributed Pull Request. It's not heavily tested, so let me know if there's issues.
